import React, { Component } from 'react';
import './Comproceci.css';

class Comproceci extends Component {
  render() {
    return (
      <div className='comprocontainer'>
        <div className='p-t'>
          <h1>Comprometido</h1>
        </div>
        <div style={{flexDirection: 'column', display: 'flex', width: '475rem'}}>
          <div className='compro-row'>
            <p className='compro-w'><b>Fondo</b></p>
            <p className='compro-w'><b>U.P</b></p>
            <p className='compro-w'><b>Partida</b></p>
            <p className='compro-w1'><b>Total</b></p>
            <p className='compro-w2'><b>Mes de Conciliación</b></p>
            <p className='compro-w1'><b>Fecha</b></p>
            <p className='compro-w1'><b>Proyecto</b></p>
            <p className='compro-w'><b>U.P</b></p>
            <p className='compro-w'><b>Partida</b></p>
            <p className='compro-w1'><b>Monto</b></p>
            <p className='compro-w3'><b>No. de Oficio de aut de recuersos</b></p>
            <p className='compro-w4'><b>Nombre del Proyecto</b></p>
            <p className='compro-w4'><b>Clave Presupuestal armonizada</b></p>
            <p className='compro-w1'><b>CR</b></p>
            <p className='compro-w2'><b>Fecha de pago</b></p>
            <p className='compro-w2'><b>Mes de pago</b></p>
            <p className='compro-w2'><b>Fecha de aplicación</b></p>
            <p className='compro-w5'><b>Proveedor</b></p>
            <p className='compro-w2'><b>Tipo de fondo</b></p>
            <p className='compro-w2'><b>Fecha de CR</b></p>
            <p className='compro-w'><b>CFDI</b></p>
            <p className='compro-w1'><b>-</b></p>
            <p className='compro-w2'><b>COMPROB PARTIDA</b></p>
            <p className='compro-w1'><b>Clave</b></p>
            <p className='compro-w'><b>Proy</b></p>
            <p className='compro-w'><b>-</b></p>
            <p className='compro-w1'><b>-</b></p>
            <p className='compro-w4'><b>Partida</b></p>
            <p className='compro-w'><b>-</b></p>
            <p className='compro-w'><b>-</b></p>
            <p className='compro-w4'><b>-</b></p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>
          <div className='compro-row'>
            <p className='compro-w'>1</p>
            <p className='compro-w'>1</p>
            <p className='compro-w'>211002</p>
            <p className='compro-w1'>$ 1.344,00</p>
            <p className='compro-w2'>-</p>
            <p className='compro-w1'>17/01/19</p>
            <p className='compro-w1'>AU001</p>
            <p className='compro-w'>-</p>
            <p className='compro-w'>-</p>
            <p className='compro-w1'>-</p>
            <p className='compro-w3'>SFP-CPF-01-0105/2019</p>
            <p className='compro-w4'>Atención y seguimiento a peticiones recibidas en el despacho del procurador.</p>
            <p className='compro-w4'>26-30-01-6201010-01-211002-1-02-02-404-00-E0018-01-002-AU001-001-B07-85000-00-00-D5-C5-0194-00-01-PF-01-01</p>
            <p className='compro-w1'>100926</p>
            <p className='compro-w2'>31-ene-19</p>
            <p className='compro-w2'>Enero</p>
            <p className='compro-w2'>10</p>
            <p className='compro-w5'>Procuraduria General de Justicia</p>
            <p className='compro-w2'>Fondo revolvente</p>
            <p className='compro-w2'>28-ene-19</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>211002</p>
            <p className='compro-w2'>0</p>
            <p className='compro-w1'>01</p>
            <p className='compro-w'>01</p>
            <p className='compro-w'>0</p>
            <p className='compro-w1'>6201010</p>
            <p className='compro-w4'>Gastos de oficina</p>
            <p className='compro-w'>Folio</p>
            <p className='compro-w'>por</p>
            <p className='compro-w4'>Folio 1 por Gastos de oficina</p>
          </div>

        </div>
      </div>
    );
  }
}

export default Comproceci;
